# Generated by Django 4.1.1 on 2022-10-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
